[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
hock_add = '''
    let g:vimfiler_as_default_explorer=1
    let g:vimfiler_safe_mode_by_default0
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_vert_resize = 1
    let g:winresizer_horiz_resize = 1
 '''

[[plugins]]
repo= 'thinca/vim-quickrun'
hook_add='''
    nmap <Leader>r <plug>(quickrun)
'''
